@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDc5MDk3NjksInNjb3BlIjpbInVzZXIiXSwidWlkIjoia2VQWHJnbjUifQ.iJnl6JjUMnKl7EHgLtJPoZI7iTBoSOj0KcGba4KuybI
@baseUrl = http://0.0.0.0:9090

GET {{baseUrl}}/status

###
GET {{baseUrl}}/status?error=not-found

###
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
	"email": "janedoe@test.com",
	"password": "test@test"
}

###
POST {{baseUrl}}/api/users
Content-Type: application/json

{
	"firstName": "Jane",
	"lastName": "Doe",
	"phone": "+1 123 456 7896",
	"email": "janedoe6@test.com",
	"password": "test@test",
	"IsTermAndConditionAgreed": true
}

###
GET {{baseUrl}}/api/users/me
Content-Type: application/json
Authorization: {{token}}

###
GET {{baseUrl}}/api/users/kePXrgn5
Content-Type: application/json
Authorization: {{token}}

###
GET {{baseUrl}}/api/users?limit=10&page=1
Content-Type: application/json
Authorization: {{token}}

###
DELETE {{baseUrl}}/api/users/bQ7WRPe9
Content-Type: application/json
Authorization: {{token}}

