@token = Bearer 
@baseUrl = http://0.0.0.0:9090

GET {{baseUrl}}/status

###
GET {{baseUrl}}/status?error=not-found



###
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
	"email": "janedoe3@test.com",
	"password": "test@test"
}

###
POST {{baseUrl}}/api/users
Content-Type: application/json

{
	"firstName": "Jane",
	"lastName": "Doe",
	"phone": "+1 123 456 7894",
	"email": "janedoe5",
	"password": "test@test",
	"IsTermAndConditionAgreed": true
}

###
GET {{baseUrl}}/api/users/me
Content-Type: application/json
Authorization: {{token}}

###
GET {{baseUrl}}/api/users?limit=10&page=1
Content-Type: application/json
Authorization: {{token}}

###
GET {{baseUrl}}/api/users/NmPLNgv8
Content-Type: application/json
Authorization: {{token}}

###
DELETE {{baseUrl}}/api/users/bo4l3gBv
Content-Type: application/json
Authorization: {{token}}

