@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDc4NTcwMjksInNjb3BlIjpbInVzZXIiXSwidWlkIjoia2VQWHJnbjUifQ.cm3r9AJfvsNaq-l-FkJLqXQMewz98Ba6ekDv0jWdJUY
@baseUrl = http://0.0.0.0:9090

GET {{baseUrl}}/status

###
GET {{baseUrl}}/status?error=not-found



###
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
	"email": "janedoe@test.com",
	"password": "test@test"
}

###
POST {{baseUrl}}/api/users
Content-Type: application/json

{
	"firstName": "Jane",
	"lastName": "Doe",
	"phone": "+1 123 456 7894",
	"email": "janedoe4@test.com",
	"password": "test@test",
	"IsTermAndConditionAgreed": true
}

###
GET {{baseUrl}}/api/users/me
Content-Type: application/json
Authorization: {{token}}

###
GET {{baseUrl}}/api/users/NmPLNgv8
Content-Type: application/json
Authorization: {{token}}

###
GET {{baseUrl}}/api/users?limit=10&page=1
Content-Type: application/json
Authorization: {{token}}

###
DELETE {{baseUrl}}/api/users/wo4rwPBa
Content-Type: application/json
Authorization: {{token}}

